// Deep-link spec §8.1 / §12 — Expo config plugin that hosts the Solana
// Mobile Wallet Adapter in a dedicated Android activity.
//
// Following the reference RN wallet in `solana-mobile/mobile-wallet-adapter`
// (`examples/example-react-native-wallet`), MWA runs in its own
// `ReactActivity` (`launchMode="singleTask"`, own `taskAffinity`,
// bottom-sheet theme, `exported="true"`) that renders the second
// registered root component (`TakumiMwaEntrypoint`, see `index.js`).
// `getCallingPackage()` — the only OS-attested identity in the whole
// spec — is `null` unless the dApp used `startActivityForResult` into an
// activity that is not the task root, so hosting MWA in `MainActivity`
// would silently downgrade every native dApp to "unverified".
//
// Responsibilities (Android only; a no-op on iOS — the walletlib has no
// iOS sources and `solana-wallet` is NOT added to CFBundleURLSchemes):
//   1. Write `MobileWalletAdapterActivity.kt` next to `MainActivity.kt`.
//   2. Write `res/values/mwa_styles.xml` with the bottom-sheet theme.
//   3. Declare the activity in AndroidManifest.xml with the two
//      `solana-wallet` intent filters from the reference manifest plus an
//      `autoVerify` filter for `https://takumipay.xyz/mobilewalletadapter`
//      so `wallet_uri_base` can be returned as an https prefix, and a
//      private `<app scheme>-mwa` filter that the Phase 3b attestation
//      page redirects to (the MWA activity is its own task, so a return
//      through the main app scheme would land in `MainActivity`).
//   4. Include the vendored walletlib fork (`native/mwa-walletlib`, spec
//      Phase 3b origin attestation) and substitute the published
//      `com.solanamobile:mobile-wallet-adapter-walletlib` / `-common`
//      coordinates with it, so the React Native bridge (patched through
//      `patches/`) compiles against the fork.

const fs = require("node:fs");
const path = require("node:path");
const {
  withAndroidManifest,
  withDangerousMod,
  withProjectBuildGradle,
  withSettingsGradle,
} = require("expo/config-plugins");

const ACTIVITY_NAME = "MobileWalletAdapterActivity";
const COMPONENT_NAME = "TakumiMwaEntrypoint";
const THEME_NAME = "Theme.TakumiPay.MwaBottomSheet";
const VERIFIED_HOST = "takumipay.xyz";
const UL_PATH_PREFIX = "/mobilewalletadapter";

function activitySource(packageName) {
  return `package ${packageName}

import android.os.Bundle
import android.view.Gravity
import android.view.WindowManager
import com.facebook.react.ReactActivity
import com.facebook.react.ReactActivityDelegate
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.fabricEnabled
import com.facebook.react.defaults.DefaultReactActivityDelegate

/**
 * Mobile Wallet Adapter host activity (docs/deeplink-wallet-interactions-spec.md §8.1).
 * Generated by plugins/withSolanaMobileWalletAdapter.js — do not edit by hand.
 */
class ${ACTIVITY_NAME} : ReactActivity() {

  override fun getMainComponentName(): String = "${COMPONENT_NAME}"

  override fun onCreate(savedInstanceState: Bundle?) {
    val windowLayoutParams = window.attributes
    windowLayoutParams.gravity = Gravity.BOTTOM
    windowLayoutParams.flags = windowLayoutParams.flags and WindowManager.LayoutParams.FLAG_DIM_BEHIND
    window.attributes = windowLayoutParams
    // null: the walletlib reads the association URI from the launch
    // intent; restoring a saved instance would replay a dead session.
    super.onCreate(null)
  }

  override fun createReactActivityDelegate(): ReactActivityDelegate =
    DefaultReactActivityDelegate(this, mainComponentName, fabricEnabled)
}
`;
}

const STYLES_XML = `<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- Generated by plugins/withSolanaMobileWalletAdapter.js (deep-link spec §8.1). -->
    <style name="${THEME_NAME}" parent="Theme.AppCompat.Dialog">
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
        <item name="android:windowMinWidthMinor">100%</item>
        <item name="android:windowMinWidthMajor">100%</item>
        <item name="android:windowBackground">@android:color/transparent</item>
        <item name="android:windowIsTranslucent">true</item>
        <item name="android:backgroundDimEnabled">true</item>
    </style>
</resources>
`;

function writeIfChanged(file, content) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  if (fs.existsSync(file) && fs.readFileSync(file, "utf8") === content) return;
  fs.writeFileSync(file, content);
}

const withMwaSources = (config) =>
  withDangerousMod(config, [
    "android",
    (cfg) => {
      const packageName = cfg.android?.package;
      if (!packageName) {
        throw new Error(
          "[withSolanaMobileWalletAdapter] android.package is not set",
        );
      }
      const root = cfg.modRequest.platformProjectRoot;
      const javaDir = path.join(
        root,
        "app/src/main/java",
        ...packageName.split("."),
      );
      writeIfChanged(
        path.join(javaDir, `${ACTIVITY_NAME}.kt`),
        activitySource(packageName),
      );
      writeIfChanged(
        path.join(root, "app/src/main/res/values/mwa_styles.xml"),
        STYLES_XML,
      );
      return cfg;
    },
  ]);

function intentFilter(order, { browsable, data }) {
  return {
    $: {
      "android:order": String(order),
      ...(browsable && data.autoVerify ? { "android:autoVerify": "true" } : {}),
    },
    action: browsable
      ? [{ $: { "android:name": "android.intent.action.VIEW" } }]
      : [],
    category: [
      { $: { "android:name": "android.intent.category.DEFAULT" } },
      ...(browsable
        ? [{ $: { "android:name": "android.intent.category.BROWSABLE" } }]
        : []),
    ],
    data: [{ $: data.attrs }],
  };
}

const withMwaManifest = (config) =>
  withAndroidManifest(config, (cfg) => {
    const app = cfg.modResults.manifest.application?.[0];
    if (!app)
      throw new Error(
        "[withSolanaMobileWalletAdapter] no <application> in manifest",
      );
    const packageName = cfg.android?.package ?? "";
    // Mirrors `constants/appVariant.ts#APP_SCHEME` + "-mwa" (the first
    // scheme in `app.config.ts` is the variant-specific app scheme).
    const appScheme = Array.isArray(cfg.scheme) ? cfg.scheme[0] : cfg.scheme;
    if (!appScheme)
      throw new Error("[withSolanaMobileWalletAdapter] expo.scheme is unset");
    const attestScheme = `${appScheme}-mwa`;
    app.activity = (app.activity ?? []).filter(
      (a) => a.$?.["android:name"] !== `.${ACTIVITY_NAME}`,
    );
    app.activity.push({
      $: {
        "android:name": `.${ACTIVITY_NAME}`,
        "android:launchMode": "singleTask",
        "android:taskAffinity": `${packageName}.mwa`,
        "android:theme": `@style/${THEME_NAME}`,
        "android:exported": "true",
        "android:excludeFromRecents": "true",
        "android:configChanges":
          "keyboard|keyboardHidden|orientation|screenLayout|screenSize|smallestScreenSize|uiMode",
      },
      "intent-filter": [
        // Default solana-wallet URI from a browser or native dApp.
        intentFilter(1, {
          browsable: true,
          data: { attrs: { "android:scheme": "solana-wallet" } },
        }),
        // Any other uncategorised solana-wallet URI not covered above.
        intentFilter(0, {
          browsable: false,
          data: { attrs: { "android:scheme": "solana-wallet" } },
        }),
        // `wallet_uri_base` — the https prefix dApps may target instead of
        // the contended scheme. Verified through assetlinks.json.
        intentFilter(2, {
          browsable: true,
          data: {
            autoVerify: true,
            attrs: {
              "android:scheme": "https",
              "android:host": VERIFIED_HOST,
              "android:pathPrefix": UL_PATH_PREFIX,
            },
          },
        }),
        // Phase 3b: return leg of the attestation-key provisioning tab
        // (`services/transports/mwa/attestation.ts#MWA_ATTEST_RETURN_URL`).
        intentFilter(3, {
          browsable: true,
          data: {
            attrs: { "android:scheme": attestScheme, "android:host": "attest" },
          },
        }),
      ],
    });
    return cfg;
  });

const FORK_MODULE = ":mwa-walletlib";
const FORK_DIR = "../native/mwa-walletlib";
const SETTINGS_MARKER = "// TakumiPay: MWA walletlib fork (origin attestation)";
const BUILD_MARKER =
  "// TakumiPay: substitute the published MWA walletlib with the vendored fork";

const withMwaForkSettings = (config) =>
  withSettingsGradle(config, (cfg) => {
    if (!cfg.modResults.contents.includes(SETTINGS_MARKER)) {
      cfg.modResults.contents += [
        "",
        SETTINGS_MARKER,
        `include '${FORK_MODULE}'`,
        `project('${FORK_MODULE}').projectDir = new File(rootProject.projectDir, '${FORK_DIR}')`,
        "",
      ].join("\n");
    }
    return cfg;
  });

const withMwaForkSubstitution = (config) =>
  withProjectBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== "groovy") {
      throw new Error(
        "[withSolanaMobileWalletAdapter] expected a Groovy root build.gradle",
      );
    }
    if (!cfg.modResults.contents.includes(BUILD_MARKER)) {
      cfg.modResults.contents += [
        "",
        BUILD_MARKER,
        "// (docs/upstream/mwa-origin-attestation/README.md). The bridge's",
        '// `implementation "com.solanamobile:mobile-wallet-adapter-walletlib:2.0.2"`',
        "// and the AAR's own `-common` dependency both resolve to the fork.",
        "allprojects {",
        "  configurations.all {",
        "    resolutionStrategy.dependencySubstitution {",
        `      substitute module('com.solanamobile:mobile-wallet-adapter-walletlib') using project('${FORK_MODULE}') because 'TakumiPay origin-attestation fork'`,
        `      substitute module('com.solanamobile:mobile-wallet-adapter-common') using project('${FORK_MODULE}') because 'bundled into the TakumiPay fork'`,
        "    }",
        "  }",
        "}",
        "",
      ].join("\n");
    }
    return cfg;
  });

module.exports = function withSolanaMobileWalletAdapter(config) {
  return withMwaForkSubstitution(
    withMwaForkSettings(withMwaManifest(withMwaSources(config))),
  );
};
